project:
  type: book

execute: 
  freeze: auto
  error: true
  warning: false

filters: 
  - quarto-ai-helper

book:
  title: "Lecture 6: Microbiome Analysis with R"
  author: "高春辉"
  date: now
  chapters:
    - index.qmd
    - preprocess.qmd
    - taxonomy.qmd
    - alpha.qmd
    - beta.qmd
    - differ.qmd
    - network.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



