project:
  type: book

execute:
  freeze: auto
  error: true
  warning: false

filters:
  - quarto-ai-helper

engine: knitr

knitr:
  opts_chunk:
    comment: "#>"

book:
  title: "Lecture 6: Microbiome Analysis with R"
  author: "高春辉"
  date: now
  chapters:
    - index.qmd
    - preprocess.qmd
    - taxonomy.qmd
    - alpha.qmd
    - beta.qmd
    - differ.qmd
    - network.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

crossref:
  fig-title: "图"
  tbl-title: "表"
  fig-prefix: "图"
  tbl-prefix: "表"

format:
  html:
    theme: cosmo
    code-overflow: wrap
  pdf:
    documentclass: custom
    papersize: a4paper
    fontsize: 9pt
    include-in-header: preamble.tex
    code-overflow: wrap
    fig-width: 6
    fig-height: 4



